API_HOST_URL: 'https://etraining.moe.gov.sa'
ENVIRONMENT_DISPLAY_NAME: 'etraining.moe.gov.sa'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'etraining.moe.gov.sa'
FEEDBACK_EMAIL_ADDRESS: 'info@raccoongang.com'
DEBUG: true
OAUTH_CLIENT_ID: 'ade3828dbc35805ac27b'

MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true

COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }

OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true

DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
