API_HOST_URL: 'https://edxmoe.ilearnme.com'
ENVIRONMENT_DISPLAY_NAME: 'etraining.moe.gov.sa'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'etraining.moe.gov.sa'
FEEDBACK_EMAIL_ADDRESS: 'support@ilearn.ws'
DEBUG: true
OAUTH_CLIENT_ID: '0d7d01a1f2a866866285'

MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true

COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }

OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true

DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
